### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by vincentwen1995** [dair-ai/ml-visuals#2]
Glad to find these excellent visualizations just in time as I started to write my thesis. Was wondering how can I cite this work in my thesis/paper later on?

**Comment by omarsar** [comment]
This is a good question and I did not think about this when starting the project. So ideally, we would like the authors to post their information and give them the credit but you don't have to. In fact, if you are customizing your own figure you don't need to worry about citing at all as this is all open and free under MIT License.

However, if you are directly using a figure without changing anything, I may do a little research or contact the author (info in the slides) to find out if the figure was reproduced which potentially is the case for some of the figures. If this is the case, then you can simply say that you reproduced it from the original author/paper and not necessarily the person that generated the figures in the slides we provide.

**Comment by vincentwen1995** [comment]
Yeah it's kinda combined, so maybe I directly use the shape for representation vectors and customize some of the modules with my own text. Anyways I will keep an eye on your updates about this. Thank you much!
