### ISSUE TITLE
could not open the downloaded file

### ISSUE THREAD

**Issue by EmperorKaiser** [dair-ai/ml-visuals#23]
Hi, team, I tried to download the file as pptx format, but when it finished, my microsoft power point 2019 can not open it. The PPT2019 notified that the file is broken and needs to be recovered. But actually the recovery process cannot make it readable either... Anyone knows which app is able to open the slide file?
![issue1](https://user-images.githubusercontent.com/26653458/139565123-405bb858-1ef9-450d-829e-eca6159ca036.png)
![issue2](https://user-images.githubusercontent.com/26653458/139565317-7fb0cd73-c58a-4c90-ad78-c8d74ce7d72a.png)

**Comment by omarsar** [comment]
Hi @EmperorKaiser sorry for the late reply. I have tried exporting and it seems to work fine on my end.

**Comment by EmperorKaiser** [comment]
Thanks. I tried again and succeeded to get the latest version. It seems that I need to get it with VPN in PRC so that the downloaded file will not get broken during transportation.
